# Book

### Get All Books

GET localhost:3001/book

### Get One Book

GET localhost:3001/book/53

### Create Book

POST localhost:3001/book
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlVzZXIgTmFtZSIsImVtYWlsIjoidXNlckBlbWFpbC5jb20iLCJpYXQiOjE3MTE5ODA1NzIsImV4cCI6MTcxMjE1MzM3Mn0.v7z3RNPvdZ81TVjjawrLENZWe_jKzW_zwER63dkeQ2k

{
  "name": "Book Name",
  "author": "Book Author",
  "year": 2020,
  "condition": 2
}

### Update Book

PATCH localhost:3001/book/ae8ca0cb-2e97-41fc-b3b2-62d7a5abafe5
Content-Type: application/json

{
  "year": 11111,
  "condition": 5
}

### Remove Book

DELETE localhost:3001/book/37c61a4e-1a9c-4c39-b643-32901928571e


### Search Books with owner id

GET localhost:3001/book/search?owner=acb2b5b7-3102-4733-877d-a7984215a268
