name: Pull requests check

on:
  pull_request:

defaults:
  run:
    working-directory: ./backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn ci
      - run: yarn run format:verify
      - run: yarn run lint:verify
      - run: yarn run lint:types
      - run: yarn run test